# -*- mode: ruby -*-
# vi: set ft=ruby :

# base of ips that will be user
base_ip="192.168.21."

# first ip to be used
first_ip=60

# the number of pxc nodes
number_of_replicas=2

#one server is the master
number_of_nodes = number_of_replicas + 1

# create an array to store the list of ips
ips = [ "#{base_ip}#{first_ip}" ]

# build the list of ips for each node and gcomm address
(1..number_of_nodes).each do |a|
  ips.push("#{base_ip}#{first_ip}")
  first_ip += 1
end

Vagrant.configure(2) do |config|
  (1..number_of_nodes).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.host_name = "node-#{i}"
      node.vm.network "private_network", ip:ips[i]
      node.vm.provider :libvirt do |vb|
        vb.memory = 2048
        vb.cpus = 1
      end
    end
  end
end